
name: build-mingw

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        arch: [i686, x86_64]
        crt: [msvcrt, ucrt]

    outputs:
      GCC_VERSION: ${{ steps.build.outputs.GCC_VERSION }}
      MINGW_VERSION: ${{ steps.build.outputs.MINGW_VERSION }}
      GDB_VERSION: ${{ steps.build.outputs.GDB_VERSION }}
      MAKE_VERSION: ${{ steps.build.outputs.MAKE_VERSION }}

    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: install dependencies
        run: |
          sudo apt-get install --no-install-recommends -y \
            ca-certificates \
            libgmp-dev      \
            libmpc-dev      \
            libmpfr-dev     \
            libisl-dev      \
            xz-utils        \
            texinfo         \
            patch           \
            p7zip           \
            cmake           \
            make            \
            curl            \
            m4              \
            gcc             \
            g++

      - name: build
        id: build
        run: ./build.sh ${{ matrix.arch }} ${{ matrix.crt }}

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gcc-v${{ steps.build.outputs.GCC_VERSION }}-mingw-v${{ steps.build.outputs.MINGW_VERSION }}-${{ matrix.crt }}-${{ matrix.arch }}
          path: gcc-v${{ steps.build.outputs.GCC_VERSION }}-mingw-v${{ steps.build.outputs.MINGW_VERSION }}-${{ matrix.crt }}-${{ matrix.arch }}.7z
          if-no-files-found: error
          compression-level: 0

  release:
    runs-on: ubuntu-24.04
    needs: build
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:

      - name: release
        run: |
          echo 'GCC v${{ needs.build.outputs.GCC_VERSION }}'         >>notes.txt
          echo 'MinGW-w64 v${{ needs.build.outputs.MINGW_VERSION }}' >>notes.txt
          echo 'GDB v${{ needs.build.outputs.GDB_VERSION }}'         >>notes.txt
          echo 'Make v${{ needs.build.outputs.MAKE_VERSION }}'       >>notes.txt
          gh release create gcc-v${{ needs.build.outputs.GCC_VERSION }}-mingw-v${{ needs.build.outputs.MINGW_VERSION }} -R "${GITHUB_REPOSITORY}" -t 'gcc-v${{ needs.build.outputs.GCC_VERSION }}-mingw-v${{ needs.build.outputs.MINGW_VERSION }}' -F notes.txt

      - name: get artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: gcc-v${{ needs.build.outputs.GCC_VERSION }}-mingw-v${{ needs.build.outputs.MINGW_VERSION }}-*
          merge-multiple: true

      - name: upload artifacts
        run: gh release upload 'gcc-v${{ needs.build.outputs.GCC_VERSION }}-mingw-v${{ needs.build.outputs.MINGW_VERSION }}' gcc-v${{ needs.build.outputs.GCC_VERSION }}-mingw-v${{ needs.build.outputs.MINGW_VERSION }}-*.7z -R "${GITHUB_REPOSITORY}"
